# Generated by Django 4.0.4 on 2022-05-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
